export const quotes = [
  // 1–30: Deutsche Sprichwörter & Volksweisheit
  "Liebe geht durch den Magen.",
  "Essen und Trinken hält Leib und Seele zusammen.",
  "Hunger ist der beste Koch.",
  "Wer gut isst, lebt gut.",
  "Eine gute Mahlzeit ist wie ein warmes Umarmung von innen.",
  "Kochen ist die älteste Form der Liebe.",
  "Was der Bauer nicht kennt, das isst er nicht — aber er verpasst viel.",
  "Suppe macht den Koch bekannt.",
  "Erst das Essen, dann die Moral.",
  "Ein voller Bauch studiert nicht gern.",
  "Der Appetit kommt mit dem Essen.",
  "Kleine Töpfe kochen auch.",
  "Viele Köche verderben den Brei.",
  "Selbst gekocht schmeckt am besten.",
  "Wer nicht kocht, dem fehlt ein Stück vom Leben.",
  "Ein gutes Essen verbindet Menschen.",
  "Beim Kochen zeigt sich der Charakter.",
  "Was lange kocht, wird gut.",
  "Einfach kochen, herzlich essen.",
  "Das Schönste am Kochen ist das Teilen.",
  "Ein Topf voll Liebe ist besser als ein Tisch voll Luxus.",
  "Gutes Brot ist halbe Kost.",
  "Mit Geduld und Spucke fängt man eine Mucke — und macht eine gute Suppe.",
  "Wer seinen Gästen gut kocht, dem verzeiht man vieles.",
  "Die Küche ist das Herzstück des Hauses.",
  "Kochen ohne Liebe ist wie Singen ohne Seele.",
  "Ein gutes Rezept ist ein Geschenk für die Ewigkeit.",
  "Warm gegessen macht die Seele lachen.",
  "In der Küche wird Geschichte geschrieben.",
  "Ein Mahl ohne Freude ist wie ein Tag ohne Sonne.",

  // 31–60: Großmutter-Weisheiten
  "Die Oma weiß immer, was fehlt — meistens ist es Liebe und Butter.",
  "Ein gutes Gericht braucht kein Rezept — nur Erfahrung und Herz.",
  "Lass dir Zeit beim Kochen. Das Beste entsteht langsam.",
  "Die Hände der Großmutter kochen am besten.",
  "Kochen ist nicht nur Arbeit — es ist Fürsorge.",
  "Was die Oma kocht, schmeckt immer nach Zuhause.",
  "Ein selbstgekochtes Essen sagt mehr als tausend Worte.",
  "Frische Zutaten, gute Absichten — das reicht für ein wunderbares Gericht.",
  "Die Küche riecht nach Geborgenheit.",
  "Koche immer ein bisschen mehr — man weiß nie, wer noch kommt.",
  "Reste sind keine Schande, sie sind eine Einladung zur Kreativität.",
  "Das Geheimnis liegt nicht im Rezept, sondern in der Hand, die rührt.",
  "Wer mit Freude kocht, gibt mehr als nur Nahrung.",
  "Nimm dir Zeit für die Menschen, die du liebst — fang am Herd an.",
  "Ein Topf Suppe kann viel Kummer heilen.",
  "Die einfachsten Gerichte sind oft die schönsten.",
  "Kochen verbindet Generationen.",
  "Wenn das Essen fertig ist, ist auch die Liebe fertig.",
  "Jedes Rezept trägt eine Geschichte in sich.",
  "Eine Prise Salz, eine Prise Geduld — und fertig ist ein Meisterwerk.",
  "Gutes Essen braucht keinen aufwendigen Rahmen.",
  "Was aus der eigenen Küche kommt, kommt auch aus dem Herzen.",
  "Der schönste Moment in der Küche: wenn die Familie am Tisch sitzt.",
  "Kochen ist eine Sprache der Liebe, die jeder versteht.",
  "Die Mutter kocht fürs Kind, die Oma kocht fürs Herz.",
  "Alte Rezepte sind wie Briefe von der Vergangenheit.",
  "Wer kochen kann, ist nie allein.",
  "Das Beste am Essen ist das Essen — zusammen.",
  "Gib niemals ein Rezept weiter, ohne eine Erinnerung dazuzulegen.",
  "Die Küche ist der Ort, wo Magie passiert und Liebe entsteht.",

  // 61–90: Berühmte Köche & Dichter auf Deutsch
  "Kochen ist Kunst, aber alle Kunst ist nutzlos, wenn sie nicht auch nährt. — Auguste Escoffier [dt.]",
  "In der Küche lernt man das Leben kennen. — Unbekannt",
  "Ein gutes Essen ist wie ein gutes Buch — es bleibt lange in Erinnerung. — Unbekannt",
  "Kochen ist Wissenschaft und Kunst zugleich. — Ferran Adrià [dt.]",
  "Das Essen ist die Kultur, die Geschichte, die Identität eines Volkes. — — Claudia Roden [dt.]",
  "Kein Fest ohne gutes Essen, kein Essen ohne gute Gesellschaft. — Unbekannt",
  "Die Freude am Kochen ist die Freude am Leben selbst. — Unbekannt",
  "Essen ist eine Notwendigkeit, aber klug essen ist eine Kunst. — François de La Rochefoucauld [dt.]",
  "Ein Koch ist ein Künstler, dessen Leinwand der Teller ist.",
  "Kochen bedeutet, sich um andere zu kümmern. — Alain Ducasse [dt.]",
  "Das Beste, was man für seine Gesundheit tun kann, ist selbst zu kochen. — Unbekannt",
  "Essen soll Freude machen — keine Angst. — Julia Child [dt.]",
  "Man kocht nicht nur mit dem Verstand, sondern mit dem Herzen.",
  "Ein Rezept hat keine Seele — der Koch muss sie hineinbringen. — Thomas Keller [dt.]",
  "Die einfachste Mahlzeit kann das schönste Erlebnis sein.",
  "Kochen ist Vertrauen in die eigenen Hände.",
  "Beim Kochen vergesse ich alles Schwere des Tages.",
  "Ein guter Koch braucht nur wenige Zutaten — aber die müssen gut sein.",
  "Essen ist Erinnerung. — Eckart Witzigmann",
  "Der wahre Luxus ist ein Tisch voller guter Dinge und guter Menschen.",
  "Nichts verbindet so sehr wie ein gemeinsames Mahl.",
  "Das Beste am Herbst ist das Kochen mit allem, was die Erde gibt.",
  "Ein Gericht ohne Liebe ist nur Nahrung. Ein Gericht mit Liebe ist ein Erlebnis.",
  "Kochen ist Poesie in Geschmack übersetzt.",
  "Der Tisch ist der Ort, wo Familien wachsen.",
  "Frisch, einfach, herzlich — das ist gute Küche.",
  "Wer gerne kocht, der liebt das Leben.",
  "Ein Essen ohne Wein ist wie ein Tag ohne Sonne. — Brillat-Savarin [dt.]",
  "Man ist, was man isst — also koche mit Bedacht.",
  "Die Seele der Küche ist ihre Großzügigkeit.",

  // 91–120: Goethe, Schiller, Rilke & deutsche Literatur
  "Wer nichts weiß, muss alles glauben. — Marie von Ebner-Eschenbach",
  "Das Beste, was wir von der Geschichte haben, ist die Begeisterung, die sie erregt. — Goethe",
  "Nur wer die Sehnsucht kennt, weiß, was ich leide. — Goethe",
  "Des Menschen Wille ist sein Himmelreich. — Deutsches Sprichwort",
  "Alles Große in dieser Welt geschieht, weil jemand mehr tut als er muss. — Hermann Gmeiner",
  "Man soll dem Leib etwas Gutes bieten, damit die Seele Lust hat, darin zu wohnen. — Winston Churchill [dt.]",
  "Das Leben ist zu kurz für schlechtes Essen.",
  "Genuss und Maß schließen einander nicht aus. — Unbekannt",
  "Es gibt nichts Schöneres, als mit Menschen zu essen, die man liebt. — Unbekannt",
  "Der Hunger nach Liebe ist viel schwerer zu stillen als der Hunger nach Brot. — Mutter Teresa [dt.]",
  "Wer täglich kocht, übt täglich Geduld.",
  "Im Kochen liegt Meditation — man denkt nur an das Wesentliche.",
  "Gute Küche ist ehrliche Küche.",
  "Jedem Abend sein Mahl, jedem Mahl sein Dank.",
  "Nichts ist verlorene Zeit, was am Herd verbracht wird.",
  "Glück ist, wenn der Duft aus der Küche einen empfängt.",
  "Das Schönste am Winter ist ein heißer Teller Suppe.",
  "Einfachheit ist das höchste Gebot in der Küche.",
  "Heimat schmeckt nach dem Essen der Mutter.",
  "Wer gut kocht, kocht mit der Seele.",
  "Gutes Essen beginnt auf dem Markt, nicht im Supermarkt.",
  "Was wächst auf dem eigenen Boden, schmeckt immer am besten.",
  "Ein voller Bauch, ein ruhiges Herz — so beginnt ein guter Tag.",
  "In der Langsamkeit liegt der Geschmack.",
  "Kochen ist die Kunst, aus dem Alltäglichen etwas Besonderes zu machen.",
  "Wer Brot backt, backt Geduld.",
  "Alte Rezepte, neue Hände — so bleibt Tradition lebendig.",
  "Beim Essen zeigt sich, wer man wirklich ist.",
  "Eine liebevoll zubereitete Mahlzeit ist das beste Medikament.",
  "Kein Tag ist verloren, an dem man gut gegessen hat.",

  // 121–150: Englische Klassiker mit deutscher Übersetzung
  '"Cooking is one of the great gifts you can give to those you love." — Ina Garten [dt. Kochen ist eines der schönsten Geschenke, die man seinen Liebsten machen kann.]',
  '"Food is our common ground, a universal experience." — James Beard [dt. Essen ist unser gemeinsamer Boden, eine universelle Erfahrung.]',
  '"The secret ingredient is always love." — Unbekannt [dt. Die geheime Zutat ist immer Liebe.]',
  '"You don\'t have to cook fancy masterpieces — just good food from fresh ingredients." — Julia Child [dt. Koche kein Kompliziertes — nur gutes Essen aus frischen Zutaten.]',
  '"Laughter is brightest in the place where the food is." — Irisches Sprichwort [dt. Das Lachen klingt am hellsten dort, wo das Essen ist.]',
  '"One cannot think well, love well, sleep well, if one has not dined well." — Virginia Woolf [dt. Man kann nicht gut denken, lieben oder schlafen, wenn man nicht gut gespeist hat.]',
  '"Ask not what you can do for your country. Ask what\'s for lunch." — Orson Welles [dt. Frag nicht, was du für dein Land tun kannst. Frag, was es zum Mittagessen gibt.]',
  '"Cooking is at once child\'s play and adult joy." — Craig Claiborne [dt. Kochen ist zugleich Kinderspiel und Erwachsenenfreude.]',
  '"A recipe has no soul. You, as the cook, must bring soul to the recipe." — Thomas Keller [dt. Ein Rezept hat keine Seele — du musst sie hineingeben.]',
  '"Food is symbolic of love when words are inadequate." — Alan D. Wolfelt [dt. Essen ist ein Symbol der Liebe, wenn Worte nicht ausreichen.]',
  '"People who love to eat are always the best people." — Julia Child [dt. Menschen, die gerne essen, sind immer die besten Menschen.]',
  '"Cooking is like love. It should be entered into with abandon or not at all." — Harriet Van Horne [dt. Kochen ist wie Liebe — ganz oder gar nicht.]',
  '"There is no love sincerer than the love of food." — George Bernard Shaw [dt. Es gibt keine aufrichtigere Liebe als die Liebe zum Essen.]',
  '"The discovery of a new dish does more for human happiness than the discovery of a new star." — Brillat-Savarin [dt. Die Entdeckung eines neuen Gerichts macht glücklicher als die eines neuen Sterns.]',
  '"Part of the secret of success in life is to eat what you like." — Mark Twain [dt. Ein Teil des Erfolgsgeheimnisses ist, das zu essen, was man mag.]',
  '"The kitchen is the heart of every home." — Debi Mazar [dt. Die Küche ist das Herzstück jedes Hauses.]',
  '"Cooking is about passion." — Gordon Ramsay [dt. Kochen ist Leidenschaft — nichts weniger.]',
  '"Sharing food with another human being is an intimate act." — M.F.K. Fisher [dt. Essen mit jemandem zu teilen ist ein inniger Akt.]',
  '"Cookery is not chemistry. It is an art." — Marcel Boulestin [dt. Kochen ist keine Chemie. Es ist eine Kunst.]',
  '"The way to a man\'s heart is through his stomach." — Fanny Fern [dt. Der Weg zum Herzen eines Menschen führt durch den Magen.]',
  '"Good bread is the most fundamentally satisfying of all foods." — James Beard [dt. Gutes Brot ist das grundlegendste und befriedigendste aller Lebensmittel.]',
  '"After a good dinner one can forgive anybody, even one\'s own relatives." — Oscar Wilde [dt. Nach einem guten Abendessen kann man jedem vergeben, sogar seinen Verwandten.]',
  '"Worries go down better with soup." — Jüdisches Sprichwort [dt. Sorgen gehen leichter hinunter mit Suppe.]',
  '"A good meal ought to begin with hunger." — Französisches Sprichwort [dt. Eine gute Mahlzeit sollte mit Hunger beginnen.]',
  '"The pleasures of the table belong to all times and all ages." — Brillat-Savarin [dt. Die Freuden der Tafel gehören allen Zeiten und Altersgruppen.]',
  '"Real cooking is much more than following a recipe." — Thomas Keller [dt. Echtes Kochen ist viel mehr als das Befolgen eines Rezepts.]',
  '"In the childhood memories of every good cook, there\'s a large kitchen, a warm stove." — Laurie Colwin [dt. In den Kindheitserinnerungen jedes guten Kochs gibt es eine große Küche, einen warmen Herd.]',
  '"Noodles are not only amusing but delicious." — Julia Child [dt. Nudeln sind nicht nur amüsant, sondern auch köstlich.]',
  '"A recipe is a story that ends with a good meal." — Pat Conroy [dt. Ein Rezept ist eine Geschichte, die mit einer guten Mahlzeit endet.]',
  '"I cook with wine, sometimes I even add it to the food." — W.C. Fields [dt. Ich koche mit Wein — manchmal füge ich ihn sogar dem Essen hinzu.]',

  // 151–180: Österreichisch & Südtirolerisch inspiriert
  "In Österreich ist die Küche kein Handwerk — sie ist eine Herzensangelegenheit.",
  "Ein Wiener Schnitzel ist kein Gericht. Es ist ein Versprechen.",
  "Wer einen Kaiserschmarrn macht, macht auch ein Stück Kindheit.",
  "Die Südtiroler Küche ist der Beweis, dass Einfachheit Großartigkeit ist.",
  "Ein Knödel ist rund wie das Glück — er kommt immer zurück.",
  "Die Berge geben uns die besten Zutaten. Die Zeit gibt uns das beste Essen.",
  "Ein Teller Gulasch wärmt mehr als ein Mantel.",
  "Palatschinken mit Marmelade — das ist Sonntagsmorgen.",
  "Apfelstrudel riecht nach Heimweh und Wiedersehen.",
  "Die Tiroler sagen: Ein gutes Brot braucht keine Beilage.",
  "Speck, Brot, Käse — mehr braucht der Bergbauer nicht zum Glück.",
  "Tafelspitz ist kein Luxus, er ist eine Tradition.",
  "Südtiroler Schlutzkrapfen: Teig, Füllung, Liebe — in dieser Reihenfolge.",
  "Der Duft von frischem Brot aus dem Holzofen ist das schönste Lied.",
  "Ein gutes Gulasch braucht Zeit — wie alle guten Dinge.",
  "Wer Semmelknödel kann, kann kochen.",
  "Die Vinschgauer Küche ist still und stark — wie die Berge selbst.",
  "In Südtirol wird mit dem gegessen, was das Land hergibt. Nie mehr, nie weniger.",
  "Zelten ist kein Weihnachtsgebäck. Es ist ein Brief an den Winter.",
  "Ein guter Graukäse braucht Mut — den hat Südtirol genug.",
  "Was die Alm hergibt, ist alles, was man braucht.",
  "Bauernbrot aus eigenen Händen — das ist Stolz und Zufriedenheit.",
  "Die Küche der Alpen ist ehrlich: kein Schnickschnack, nur Geschmack.",
  "Ein Tirtl ist wie eine kleine Überraschung — innen das Beste.",
  "Kastaniensuppe im Herbst — das ist das Ende des Sommers, sanft verabschiedet.",
  "Wer in Südtirol zu Gast ist, ist nie ein Fremder am Tisch.",
  "Frische Luft, frische Zutaten — die Grundlage der Alpenküche.",
  "Ein Gericht aus der Heimat schmeckt überall auf der Welt am besten.",
  "Krapfen zu Fasching — weil das Leben süß sein darf.",
  "Die beste Küche entsteht dort, wo die besten Geschichten erzählt werden.",

  // 181–210: Trost & Lebensweisheit
  "Ein gutes Essen macht den schwersten Tag leichter.",
  "Wenn alles schwierig ist, beginne mit dem Kochen — danach sieht die Welt besser aus.",
  "Kochen ist Meditation für die Seele.",
  "Am Herd findet man Frieden.",
  "Ein selbstgekochtes Essen ist die liebevollste Antwort auf viele Fragen.",
  "Wenn die Welt sich dreht, halte ich mich am Topf fest.",
  "Kochen ist das einzige Handwerk, bei dem man das Ergebnis sofort genießen kann.",
  "Ein gutes Essen macht glücklich — das ist keine Philosophie, das ist Wahrheit.",
  "Die Küche ist ein Ort der Gegenwart. Hier zählt nur dieser Moment.",
  "Was aus der Erde wächst, nährt auch die Seele.",
  "Gemeinsam essen — das ist das älteste Ritual der Menschheit.",
  "Kein Rezept ist perfekt. Kein Koch ist perfekt. Das Essen aber kann es sein.",
  "Aus Fehlern beim Kochen entstehen neue Gerichte.",
  "Der beste Abend beginnt mit: 'Ich koche heute für dich.'",
  "Wer für andere kocht, vergisst für eine Weile seine eigenen Sorgen.",
  "Kochen ist der schönste Beweis dafür, dass Liebe eine Handlung ist.",
  "Ein Tisch voller Essen ist ein Tisch voller Hoffnung.",
  "Das Beste, was man einem Menschen wünschen kann: dass er nie allein isst.",
  "Wärme kommt nicht nur vom Herd — sie kommt von den Händen, die kochen.",
  "Ein gutes Essen braucht keine Bühne — nur einen vollen Tisch.",
  "Kochen verbindet das, was Worte manchmal nicht schaffen.",
  "Jede Mahlzeit ist eine neue Chance.",
  "Im Essen liegt Dankbarkeit — für die Erde, für die Arbeit, für die Zeit.",
  "Wer kocht, erschafft Momente, die bleiben.",
  "Das Essen endet, aber die Erinnerung daran bleibt ewig.",
  "Kochen ist das Schönste, was man mit seinen Händen tun kann.",
  "Ein Löffel Suppe, ein Lächeln — manchmal braucht es nicht mehr.",
  "Genieße jeden Bissen, als wäre es der erste.",
  "Was man mit Liebe kocht, wird mit Liebe gegessen.",
  "Das Beste kommt zuletzt — beim Kochen und im Leben.",

  // 211–240: Jahreszeiten & Natur
  "Im Frühling kocht die Welt Frisches — Spargel, Bärlauch, neue Hoffnung.",
  "Der Sommer schmeckt nach Tomaten, Basilikum und Zeit.",
  "Im Herbst wird die Küche reich — Kürbis, Pilze, Äpfel, warme Farben.",
  "Der Winter ruft nach Eintopf, Brot und der Gesellschaft Geliebter.",
  "Frischer Spargel im Mai ist ein kleines Wunder.",
  "Pilze sammeln im Herbst — das ist Stille und Freude in einem.",
  "Erdbeeren im Juni brauchen keine Sahne. Nur Geduld.",
  "Ein Kürbisauflauf ist der beste Beweis, dass der Herbst kein Ende, sondern ein Anfang ist.",
  "Gefrorene Beeren aus dem eigenen Garten im Winter — das ist vorausschauende Liebe.",
  "Der Geruch von frisch gemähtem Heu und frisch gebackenem Brot — das ist Sommer.",
  "Zwetschgenknödel im August — die Belohnung für die Geduld des Jahres.",
  "Marmeladekochen im Sommer ist das Einmachen von Sonnenschein.",
  "Kastanien rösten im Oktober — das Knistern, der Duft, die Wärme.",
  "Linsensuppe im Januar — einfach, nahrhaft, treu.",
  "Frühlingsrollen aus frischem Gemüse — der erste Gruß der neuen Saison.",
  "Saure Gurken aus dem Glas im Winter — der Geschmack des letzten Sommers.",
  "Weihnachtsplätzchen backen ist nicht Arbeit — es ist Vorfreude.",
  "Ein Glühwein im Winter wärmt von innen wie kein anderes Getränk.",
  "Grüner Salat im März — der erste Schritt aus dem Winter.",
  "Omas Beerenmarmelade ist der Sommer im Glas.",
  "Rotkohl im November ist die Farbe des Trostes.",
  "Frische Butter im Frühling schmeckt anders — nach Gras und Versprechen.",
  "Rhabarber im April: sauer, wach, lebendig.",
  "Ein Pflaumenkuchen im September ist das letzte Versprechen des Sommers.",
  "Wirsing im Winter ist unscheinbar und wunderbar zugleich.",
  "Frisch gepresster Apfelsaft im Herbst — dicker, süßer, ehrlicher.",
  "Marillenmarmelade: Sommer eingekocht, Winter verschenkt.",
  "Ein gutes Linsengericht schmeckt im Dezember wie keine andere Jahreszeit.",
  "Haselnüsse sammeln im Herbst — die Natur gibt ihren letzten Gruß.",
  "Frühlingszwiebeln auf dem Butterbrot — einfacher geht's nicht.",

  // 241–270: Brot, Eintopf & einfaches Glück
  "Brot backen ist ein Akt der Geduld und des Vertrauens.",
  "Sauerteig braucht Pflege wie eine Pflanze — und gibt viel zurück.",
  "Ein frisches Brot ist mehr wert als viele Worte.",
  "Der Duft von frisch gebackenem Brot ist das freundlichste Willkommen.",
  "Hausgemachtes Brot schneidet man langsamer — aus Respekt.",
  "Brot teilen ist der älteste Ausdruck von Gemeinschaft.",
  "Ein einfaches Butterbrot kann der Höhepunkt eines langen Tages sein.",
  "Selbstgebackenes Brot hat mehr Seele als jedes andere Essen.",
  "Brot mit Salz und einem Glas Wasser — so beginnt Gastfreundschaft.",
  "Wer Brot backen kann, fürchtet keinen Winter.",
  "Ein guter Eintopf braucht keine Bühne — nur einen Löffel.",
  "Eintopf ist demokratisch: Alles kommt zusammen und wird gleich.",
  "Eine Suppe ist der ehrlichste Ausdruck von Küche.",
  "Kein Eintopf schmeckt am ersten Tag am besten.",
  "Linsen, Möhren, ein bisschen Majoran — und der Tag wird besser.",
  "Kartoffelsuppe ist die Mutter aller Suppen.",
  "Ein Topf Bohnensuppe ist ein kleines Versprechen ans Leben.",
  "Wer eine gute Suppe kochen kann, braucht kein Kochbuch.",
  "Suppe hat keine Jahreszeit — sie hat nur Bedarf.",
  "Ein leerer Topf, ein voller Bauch — so soll es sein.",
  "Erbsensuppe mit geräuchertem Speck: der Beweis, dass Simplizität gewinnt.",
  "Der beste Eintopf ist der, den jemand für dich gekocht hat.",
  "Reste in den Topf — die beste Erfindung der Großmutter.",
  "Tomatensuppe an einem regnerischen Tag: wärmer als jede Decke.",
  "Gulaschsuppe ist kein Gericht — sie ist eine Umarmung.",
  "Eine Rindssuppe klärt den Kopf und wärmt die Seele.",
  "Gemüsesuppe mit Einlage: ehrlich, einfach, unschlagbar.",
  "Minestrone — weil Vielfalt in einem Topf die beste Metapher des Lebens ist.",
  "Grießklößchensuppe: die Kindheit in einer Schüssel.",
  "Was über Nacht zieht, schmeckt am nächsten Tag doppelt so gut.",

  // 271–300: Abschließende Weisheiten & Segen
  "Möge dein Tisch immer voll sein und dein Herz noch voller.",
  "Guten Hunger — und noch bessere Gesellschaft.",
  "Koche mit Freude, esse mit Dankbarkeit.",
  "Ein Segen für die Hände, die diese Mahlzeit bereitet haben.",
  "Essen ist das schönste Ding, das Menschen verbindet.",
  "Jedes Mahl ist ein kleines Fest — wenn man es so sieht.",
  "Das Leben ist zu kurz für mittelmäßiges Essen.",
  "Möge jedes Gericht, das du kochst, voller Liebe sein.",
  "Beim Essen vergisst man die Zeit — das ist kein Verlust.",
  "Ein Rezept ohne Variationen ist ein Lied ohne Improvisation.",
  "Kochen ist das tägliche Wunder, das wir oft übersehen.",
  "Das Beste an Fehlern in der Küche: Man kann es nächstes Mal besser machen.",
  "Mögest du immer jemanden haben, mit dem du dein Essen teilen kannst.",
  "Ein gut gedeckter Tisch ist das erste Zeichen von Würde.",
  "Die Küche ist dort, wo Liebe in Aromen verwandelt wird.",
  "Kochen für andere ist die reinste Form der Großzügigkeit.",
  "Vergiss nie: Gutes Essen braucht gute Laune beim Kochen.",
  "Alles, was man mit Geduld und Herz kocht, wird gut.",
  "Das Rezept steht im Buch — die Liebe kommt von dir.",
  "Was man teilt, verdoppelt sich. Besonders beim Essen.",
  "Ein gutes Essen beginnt mit einem guten Einkauf.",
  "Dankbarkeit beim Essen ist der beste Anfang jeder Mahlzeit.",
  "Kochen ist ein tägliches Geschenk an die Menschen, die man liebt.",
  "Ein warmer Teller Essen kann mehr trösten als viele Worte.",
  "Was die Hände kochen, baut Brücken zwischen Herzen.",
  "Gutes Essen braucht keine Perfektion — nur Ehrlichkeit.",
  "Jede Mahlzeit ist ein neuer Anfang.",
  "Die schönste Uhrzeit ist die, wenn das Essen fertig ist.",
  "Möge dein nächstes Rezept das schönste werden, das du je gekocht hast.",
  "Guten Appetit — und vor allem: gute Menschen um den Tisch.",
];

export const todayQuote = quotes[Math.floor(Math.random() * quotes.length)];
